#!/usr/bin/env bash
set -euo pipefail

########################################
# Interactive Package Selection
########################################

CONFIG_FILE=".package-categories"

# Colors
BLUE='\033[1;34m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
  printf "\n${BLUE}[INFO]${NC} %s\n" "$1"
}

success() {
  printf "${GREEN}[✓]${NC} %s\n" "$1"
}

########################################
# Show current selection
########################################

show_current() {
  echo ""
  echo "╔════════════════════════════════════════╗"
  echo "║     Package Category Selection         ║"
  echo "╚════════════════════════════════════════╝"
  echo ""
  
  if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    
    echo "Current selection:"
    echo ""
    
    [ "$INSTALL_ESSENTIALS" = "true" ] && success "Essential tools" || echo "[ ] Essential tools"
    [ "$INSTALL_LANGUAGES" = "true" ] && success "Programming languages" || echo "[ ] Programming languages"
    [ "$INSTALL_DEV_TOOLS" = "true" ] && success "Development tools" || echo "[ ] Development tools"
    [ "$INSTALL_BROWSERS" = "true" ] && success "Browsers" || echo "[ ] Browsers"
    [ "$INSTALL_EDITORS" = "true" ] && success "Editors & IDEs" || echo "[ ] Editors & IDEs"
    [ "$INSTALL_COMMUNICATION" = "true" ] && success "Communication apps" || echo "[ ] Communication apps"
    [ "$INSTALL_PRODUCTIVITY" = "true" ] && success "Productivity apps" || echo "[ ] Productivity apps"
    [ "$INSTALL_MEDIA" = "true" ] && success "Media apps" || echo "[ ] Media apps"
    [ "$INSTALL_WINDOW_MANAGERS" = "true" ] && success "Window managers" || echo "[ ] Window managers"
    [ "$INSTALL_FONTS" = "true" ] && success "Developer fonts" || echo "[ ] Developer fonts"
    [ "$INSTALL_ZSH_PLUGINS" = "true" ] && success "Zsh plugins" || echo "[ ] Zsh plugins"
    [ "$INSTALL_OPTIONAL" = "true" ] && success "Optional/Fun tools" || echo "[ ] Optional/Fun tools"
  else
    echo "No configuration found. Will use defaults."
  fi
  echo ""
}

########################################
# Interactive selection
########################################

ask_category() {
  local category="$1"
  local description="$2"
  local default="${3:-y}"
  
  local prompt
  if [ "$default" = "y" ]; then
    prompt="[Y/n]"
  else
    prompt="[y/N]"
  fi
  
  read -p "Install $description? $prompt " answer
  answer=${answer:-$default}
  
  case $answer in
    [Yy]* ) echo "true" ;;
    [Nn]* ) echo "false" ;;
    * ) echo "$default" ;;
  esac
}

interactive_select() {
  echo ""
  echo "╔════════════════════════════════════════╗"
  echo "║  Interactive Package Selection         ║"
  echo "╚════════════════════════════════════════╝"
  echo ""
  log "Select which package categories to install"
  log "Press Enter to accept default [Y/n] or [y/N]"
  echo ""
  
  INSTALL_ESSENTIALS=$(ask_category "essentials" "Essential tools (git, curl, wget)" "y")
  INSTALL_LANGUAGES=$(ask_category "languages" "Programming languages (Node, Go, Python)" "y")
  INSTALL_DEV_TOOLS=$(ask_category "dev-tools" "Development tools (Docker, Postman, etc)" "y")
  INSTALL_BROWSERS=$(ask_category "browsers" "Browsers (Chrome, Firefox, Arc)" "y")
  INSTALL_EDITORS=$(ask_category "editors" "Editors & IDEs (VS Code, Cursor)" "y")
  INSTALL_COMMUNICATION=$(ask_category "communication" "Communication (Slack, Teams)" "y")
  INSTALL_PRODUCTIVITY=$(ask_category "productivity" "Productivity (Figma, Obsidian)" "y")
  INSTALL_MEDIA=$(ask_category "media" "Media apps (Spotify, VLC)" "n")
  INSTALL_WINDOW_MANAGERS=$(ask_category "window" "Window managers (Rectangle, Raycast)" "y")
  INSTALL_FONTS=$(ask_category "fonts" "Developer fonts" "y")
  INSTALL_ZSH_PLUGINS=$(ask_category "zsh" "Zsh plugins & themes" "y")
  INSTALL_OPTIONAL=$(ask_category "optional" "Optional/Fun tools (figlet, lolcat)" "n")
  
  # Save to config file
  cat > "$CONFIG_FILE" << EOF
# Package Categories Configuration
# Generated by select-packages.sh

INSTALL_ESSENTIALS=$INSTALL_ESSENTIALS
INSTALL_LANGUAGES=$INSTALL_LANGUAGES
INSTALL_DEV_TOOLS=$INSTALL_DEV_TOOLS
INSTALL_BROWSERS=$INSTALL_BROWSERS
INSTALL_EDITORS=$INSTALL_EDITORS
INSTALL_COMMUNICATION=$INSTALL_COMMUNICATION
INSTALL_PRODUCTIVITY=$INSTALL_PRODUCTIVITY
INSTALL_MEDIA=$INSTALL_MEDIA
INSTALL_WINDOW_MANAGERS=$INSTALL_WINDOW_MANAGERS
INSTALL_FONTS=$INSTALL_FONTS
INSTALL_ZSH_PLUGINS=$INSTALL_ZSH_PLUGINS
INSTALL_OPTIONAL=$INSTALL_OPTIONAL
EOF
  
  echo ""
  success "Configuration saved to $CONFIG_FILE"
  echo ""
  show_current
}

########################################
# Preset configurations
########################################

preset_minimal() {
  cat > "$CONFIG_FILE" << EOF
# Minimal preset
INSTALL_ESSENTIALS=true
INSTALL_LANGUAGES=true
INSTALL_DEV_TOOLS=false
INSTALL_BROWSERS=false
INSTALL_EDITORS=true
INSTALL_COMMUNICATION=false
INSTALL_PRODUCTIVITY=false
INSTALL_MEDIA=false
INSTALL_WINDOW_MANAGERS=false
INSTALL_FONTS=false
INSTALL_ZSH_PLUGINS=true
INSTALL_OPTIONAL=false
EOF
  success "Minimal preset applied"
}

preset_developer() {
  cat > "$CONFIG_FILE" << EOF
# Developer preset
INSTALL_ESSENTIALS=true
INSTALL_LANGUAGES=true
INSTALL_DEV_TOOLS=true
INSTALL_BROWSERS=true
INSTALL_EDITORS=true
INSTALL_COMMUNICATION=true
INSTALL_PRODUCTIVITY=true
INSTALL_MEDIA=false
INSTALL_WINDOW_MANAGERS=true
INSTALL_FONTS=true
INSTALL_ZSH_PLUGINS=true
INSTALL_OPTIONAL=false
EOF
  success "Developer preset applied"
}

preset_full() {
  cat > "$CONFIG_FILE" << EOF
# Full preset
INSTALL_ESSENTIALS=true
INSTALL_LANGUAGES=true
INSTALL_DEV_TOOLS=true
INSTALL_BROWSERS=true
INSTALL_EDITORS=true
INSTALL_COMMUNICATION=true
INSTALL_PRODUCTIVITY=true
INSTALL_MEDIA=true
INSTALL_WINDOW_MANAGERS=true
INSTALL_FONTS=true
INSTALL_ZSH_PLUGINS=true
INSTALL_OPTIONAL=true
EOF
  success "Full preset applied"
}

########################################
# Main menu
########################################

show_menu() {
  echo ""
  echo "╔════════════════════════════════════════╗"
  echo "║     Package Selection Tool             ║"
  echo "╚════════════════════════════════════════╝"
  echo ""
  echo "1) Interactive selection (choose each category)"
  echo "2) Preset: Minimal (essentials only)"
  echo "3) Preset: Developer (recommended)"
  echo "4) Preset: Full (everything)"
  echo "5) Show current selection"
  echo "6) Edit config file manually"
  echo "7) Exit"
  echo ""
  read -p "Choose an option [1-7]: " choice
  
  case $choice in
    1) interactive_select ;;
    2) preset_minimal && show_current ;;
    3) preset_developer && show_current ;;
    4) preset_full && show_current ;;
    5) show_current ;;
    6) ${EDITOR:-vim} "$CONFIG_FILE" ;;
    7) echo "Bye!"; exit 0 ;;
    *) echo "Invalid option"; show_menu ;;
  esac
}

########################################
# Run
########################################

main() {
  # Handle command line arguments
  case "${1:-}" in
    --show)
      show_current
      exit 0
      ;;
    --minimal)
      preset_minimal
      show_current
      exit 0
      ;;
    --developer)
      preset_developer
      show_current
      exit 0
      ;;
    --full)
      preset_full
      show_current
      exit 0
      ;;
    --help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "OPTIONS:"
      echo "  --show       Show current selection"
      echo "  --minimal    Apply minimal preset"
      echo "  --developer  Apply developer preset (recommended)"
      echo "  --full       Apply full preset"
      echo "  --help       Show this help"
      echo ""
      echo "Run without options for interactive menu"
      exit 0
      ;;
    "")
      show_menu
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run with --help for usage"
      exit 1
      ;;
  esac
}

main "$@"

